### ISSUE TITLE
Organize folders to support multiple dotnet core projects

### ISSUE THREAD

**Issue by AndreiBozantan** [diffix/explorer#10]
Also, as a more general comment: we are going to need multiple dotnet core projects. Probably some class libraries, some console applications for tests etc. Isn't it common to put all the individual apps under a `src/Component` directory, and then have a top level solution file?

_Originally posted by @sebastian in https://github.com/diffix/explorer/pull/5#issuecomment-571530372_

**Comment by AndreiBozantan** [comment]
@sebastian  When doing this, I am also thinking to rename the project to `explorer.api`. What do you think about this?

**Comment by sebastian** [comment]
Sounds like a good move! 👍
