### ISSUE TITLE
Automatic linting

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#11]
Is there some automatic C# linter we can use?
This is an issue along the lines of automatic formatting that is described in https://github.com/diffix/explorer/issues/2. 

I would like to automate away as much crap as possible so we get to a consistent and clean code base with minimal effort.

I would like to see things such as it complaining about:
- too long lines (say exceeding 120 characters)
- unused variables
- unused imports
- non-idiomatic constructs etc

Once we have this in place I would like linting to be checked by Travis too.

**Comment by sebastian** [comment]
Just to expand a little on the above: my goal is to have all the boring tedious minutia automated away so pull-requests can end up being solely about content and algorithm and design.

**Comment by AndreiBozantan** [comment]
I think that we can solve linting and also code formatting (#2)  by using [StyleCope Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers), which seems to be the preferred way. There is another project which seems interesting [Roslynator](https://github.com/josefpihrt/roslynator). Both of them are using the Roslyn compiler. I will try them both and also check if they integrate well with VSCode.

**Comment by AndreiBozantan** [comment]
solved with pull request #23
