### ISSUE TITLE
Sanitize results produced by the TextColumnExplorer

### ISSUE THREAD

**Issue by AndreiBozantan** [diffix/explorer#141]
We should add some additional processing in the TextColumnExplorer in order to remove strings (or substrings) that might be offensive.

**Comment by sebastian** [comment]
Here is a lift of "bad words" that we could use: http://www.bannedwordlist.com

Maybe let's add a quick filter to ensure they aren't present, and then leave it at that?

**Comment by AndreiBozantan** [comment]
closed with #361
