### ISSUE TITLE
Python Aircloak library

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#147]
In the [python covid jupyter notebook](https://www.kaggle.com/dlennon/aircloak-basics) @dandanlen created some light scaffolding for working with Aircloak using the psycopg2 library and pandas.

We should package these utilities into a small Aircloak library that can be installed using pip. 
This looks good and simplifies working with Aircloak when using jupyter notebooks.

This should also be an open source library.

**Comment by dandanlen** [comment]
Work on this has begun [here](https://github.com/diffix/aircloak-tools).

Closing this issue, any further requirements can be logged in the repo for the python project.
