### ISSUE TITLE
Expand API to support synthesizing multiple columns

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#148]
For phase two of our explorer project we want to be able to explore tables.
As discussed in our Explorer meeting on the 19th of May we agreed that the current API can be modified such that it takes an array of columns rather than a single column.

Changes:
- Instead of a single column to explore, an array of columns should be provided
- to keep the semantics clear and obvious an empty array should indicates that nothing should be done (i.e. is effectively a noop)
- if the user wants the full table explored, then the column names array should include all the columns

The output should consist of:
- the explorations of the individual columns as we have it today, with sample values (synthesized or not) for that specific column
- a synthesized table containing all the columns specified in the request (in the order they were requested). This synthesized table will correspond to what one would get if one were to run a query such as `SELECT * FROM table LIMIT X`. 

The first iteration of this API uses the individual column exploration functionality as it stands today.

@gampleman: please note this pending API change.

**Comment by sebastian** [comment]
What's the progress here? @AndreiBozantan you assigned this to yourself a full month ago, and there doesn't seem to be much progress thus far?

**Comment by AndreiBozantan** [comment]
closed by #172
