### ISSUE TITLE
Decide on the name of a famous (enough) explorer whose name starts with a B

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#150]
This will be the name of the version that follows Armstrong.

**Comment by AndreiBozantan** [comment]
Buzz

**Comment by AndreiBozantan** [comment]
Other options:
https://en.wikipedia.org/wiki/Willem_Barentsz
https://en.wikipedia.org/wiki/Vitus_Bering

**Comment by dandanlen** [comment]
A couple of outsiders (with cool names):
[Bungaree](https://en.wikipedia.org/wiki/Bungaree)
[Bustamante](https://en.wikipedia.org/wiki/Jos%C3%A9_de_Bustamante_y_Guerra)

**Comment by sebastian** [comment]
> Buzz, and of course, Collins after that

Buzz would have my vote too. If you want to name it something else, please debate it amongst yourselves.
