### ISSUE TITLE
Multi-column correlations and dependencies

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#151]
When synthesizing values for tables, we should start taking into account inter-column dependencies and correlations. This will for example allow us to capture relationships such as those between a country and the continent to which it belongs, or the make and model of a car.
While it's quite simple to do for categorical values, it becomes more challenging for overlapping numerical distributions (say correlation between height and gender, or lat and lng). It is however doable.

Let's start small and only consider column pair correlations, and furthermore let's start with categorical values as a first deliverable.

**Comment by dandanlen** [comment]
Closing this, pairwise correlations are available since #316
