### ISSUE TITLE
Jupyter client update for api changes

### ISSUE THREAD

**Issue by dandanlen** [diffix/explorer#174]
The Jupyter client needs to be updated for compatibility with multi-column requests and return values.

**Comment by sebastian** [comment]
Will the Jupiter client work at all at present?

**Comment by dandanlen** [comment]
I have been planning on ripping it out of this project. I used the python modules from this project for [`aircloak-tools`](https://github.com/diffix/aircloak-tools), which I recently updated to include a basic module for using Diffix Explorer. All that's left to do is to tidy up and add the jupyter notebook example to that project.

**Comment by dandanlen** [comment]
(But to answer your question, it doesn't work because it doesn't know about api versioning)

**Comment by sebastian** [comment]
Decision is to:
- remove code, rather than fix it

**Comment by dandanlen** [comment]
#359 closes this. 

The existing examples have been updated and moved here:
https://github.com/diffix/explorer-jupyter-examples
