### ISSUE TITLE
Change return type of EmailCheckComponent

### ISSUE THREAD

**Issue by dandanlen** [diffix/explorer#179]
I think we should avoid using primitive types as the type argument for `ExplorerComponent<>`. The type arg should be something unique to the component. 

For example, in this case there is another `ExplorerComponent<bool>` elsewhere in the code (EmailCheckComponent) - this will cause confusion when the dependency injector resolves class instances. (I suspect you might get strange results when you run this on a `text` column).

I would suggest defining a private `Result` or `ExplorationMetadata` class containing the Exploration info. We will add more items to this (I have a branch ready where we can insert the git commit hash and ref from the docker image).

_Originally posted by @dandanlen in https://github.com/diffix/explorer/pull/175_

**Comment by dandanlen** [comment]
See also [this comment](https://github.com/diffix/explorer/pull/175#discussion_r447579477)

We should add the `class` constraint the to the generic type parameter in `ExplorerComponent`.

**Comment by AndreiBozantan** [comment]
closed with #189
