### ISSUE TITLE
Support specifying the level of parallelism

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#192]
Currently the backlog in one of our systems looks like this:

![Screen Shot 2020-07-14 at 14 29 10](https://user-images.githubusercontent.com/1089/87425917-bfd46200-c5de-11ea-89a9-32df1e93d7dd.png)

Since explorer queries are treated like any other query we have now effectively created a GIANT pile of queued queries which are ahead of any user query that might be issued. As such we have effectively done a DoS attack against our system.

It would be good if one could specify that Explorer should only ever run N concurrent queries against an endpoint.

**Comment by dandanlen** [comment]
I'll take a look at this this afternoon. My initial thought is that it might be tricky to have a rate limit per endpoint, much easier to have a rate limit set per request. The reason being: Every requested exploration runs in its own scope, so I don't think there is a clean way to share the number of in-flight requests globally. 

Either way I'm sure we can get the number down from >300 ;)

**Comment by sebastian** [comment]
Yeah, not without semaphore magic...

**Comment by dandanlen** [comment]
This looks promising:
https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim?view=netcore-3.1

**Comment by AndreiBozantan** [comment]
Maybe setting the TPL thread pool size would help with this https://stackoverflow.com/questions/11075320/using-tpl-how-do-i-set-a-max-threadpool-size

**Comment by dandanlen** [comment]
I just opened a PR (#198) with a fix that I think it should work... However short of just letting it loose on the `air` server I'm not sure how best to test it. 

@AndreiBozantan please let me know what you think.

Btw. I don't think the pool size is the issue since a single thread can service multiple async/await requests concurrently. ie. the number of concurrent requests is pretty much independent of the number of threads.

**Comment by dandanlen** [comment]
Closing this for now - PR #198 has been merged, the explorer is now restricted to 10 concurrent queries per `air` server.
