### ISSUE TITLE
Add a separate `Status` field for each column exploration.

### ISSUE THREAD

**Issue by dandanlen** [diffix/explorer#199]
Currently we provide a status for the exploration as a whole, ie. all registered `MetricsPublisher` components. If any of these errors, the status as whole is `Error`. It would be useful to have more fine-grained access to the status of each component.

_Originally posted by @AndreiBozantan in https://github.com/diffix/explorer/diffs_

**Comment by AndreiBozantan** [comment]
Closed with #202.
