### ISSUE TITLE
Setup automatic code formatter

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#2]
I would like code formatting to be a topic about which we never need to discuss or think.
Many languages have code formaters built in. They range from the enforced formatting in go, to the optional formatting in Elixir.

- Is there a de-facto standard formater for C#, if so which is it?
- It should be setup so it automatically runs on save in the default development environment
- If the formater required rules to be specified then those rules should be part of this repo
- Travis CI should reject code that hasn't been formatted properly

**Comment by AndreiBozantan** [comment]
solved with pull request #23

**Comment by sebastian** [comment]
@AndreiBozantan a trick is to add something like "Closes #23" in the description of your pull-request. That way the issue automatically gets closed when the pull-request is merged with a reference to the pull-request in the issue.
