### ISSUE TITLE
Add timestamp to logs

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#256]
Currently you can't really tell when a log entry was made. This makes it difficult to find the right place in the log if you are looking for something happening at around a certain time.

**Comment by dandanlen** [comment]
This (or similar) looks like it should work:

```csharp
.AddLogging(opt =>
     {
         opt.AddConsole(c =>
         {
            c.TimestampFormat = "[HH:mm:ss] ";
         });
```
    })

**Comment by sebastian** [comment]
Please include the date too.
