### ISSUE TITLE
Text value no capturing non-anonymized values

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#326]
Clinic dataset, prescriptions table, `display_startdatetime` column.
There are plenty of non-anonymized values in the result ([query result link](https://demo.aircloak.com/permalink/private/query/SFMyNTY.g2gDaANkAAdwcml2YXRlZAAFcXVlcnltAAAAJGU0Yjg5MDQzLTU4NTEtNGQxMC04ZmJhLTJhNGM5ZmMxYmQ2YW4GAG9YY251AWIAAVGA.RdZjxuiuGb7ALmG6QNemrkBn9Oifq3w7wRt8zkK_grU)), but none are captured by explorer, and hence the sample values are synthesized.

**Comment by sebastian** [comment]
The same is the case for the `firstname` column in the `patients` table.
There are plenty of non-anonymized firstnames returned, but the explorer data only shows synthetic data instead of real values. In fact it does not contain any information about real names existing.

([query result link](https://demo.aircloak.com/permalink/private/query/SFMyNTY.g2gDaANkAAdwcml2YXRlZAAFcXVlcnltAAAAJGE1M2RhMThjLTM5MWQtNDJiYi1iZmNmLWQ0ZWIzZWY4OTYxZG4GAN-dZm51AWIAAVGA.EgFKp1egRgV8W10D1j-7eaPpvM2AIel4fMUxhO5Ng9c))

**Comment by sebastian** [comment]
Yet another example is `city` in the `addresses` table. Lots of un-anonymized values, but none provided in the returned data.

**Comment by AndreiBozantan** [comment]
fixed with #329
