### ISSUE TITLE
Mention 31-column limit in the README

### ISSUE THREAD

**Issue by dandanlen** [diffix/explorer#348]
See description in issue #345

For the time being it's probably sufficient to describe this limitation in the docs.

_Originally posted by @sebastian in https://github.com/diffix/explorer/issues/345#issuecomment-721044522_

**Comment by sebastian** [comment]
Sorry, I think I might have been confusing in my original issue.
My goal would be:
- when doing multi-column analyses ignore all columns beyond the 31 supported ones, but still do multi-column analysis for those
- document this being a limitation in the docs.
