### ISSUE TITLE
Text columns: some have common values others not

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#355]
Take the `Addresses` table of the `Clinic` dataset.
The `province` columns lists distinct values, the `city` does not. Both clearly were able to produce some values.

The only difference is see is that one is considered categorical, the other not. Is that what causes this?

Bot should list some distinct values.

**Comment by dandanlen** [comment]
I think we have been thinking the same thing - I decided it made sense to list common values even if the column was judges as non-categorical. Is this effectively what you are suggesting?

If so, this will be fixed with the latest PR #357

**Comment by sebastian** [comment]
>  Is this effectively what you are suggesting?

Indeed that's what I was hoping for! 
Great to hear it is already implemented!
