### ISSUE TITLE
Create a formal schema for the API

### ISSUE THREAD

**Issue by AndreiBozantan** [diffix/explorer#78]
After discussing some related topics we decided to use a strongly-typed data model for the returned metrics.
In order to help the consumers of the API, we should also have a schema (e.g. JSON schema, Protocol Buffers, ...)  that formally describes the input and output data handled by the service; this should be part of the documentation.
One idea is to define the internal data models in C# and during the deployment process to generate the formal schema from the C# code (instead of the more common approach to generate the C# code from the schema). This will allow us to keep the development and build process simple and straightforward by avoiding the use of additional tools that generate C# code.

**Comment by dandanlen** [comment]
Linking #76 to illustrate the motivation for this.

**Comment by AndreiBozantan** [comment]
Closed with #298.
