### ISSUE TITLE
Ideas for pattern extraction from text

### ISSUE THREAD

**Issue by dandanlen** [diffix/explorer#85]
Here we can discuss ideas for extracting common patterns from textual columns - this can also apply to related patterns from numerical columns (such as number and distribution of digits). 

So far we have character counts, extraction of common suffixes and prefixes. We also have an implementation of an extractor for email addresses (-> domain names, tlds). The goal is to generalise this to more use cases.

**Comment by AndreiBozantan** [comment]
Using the common suffixes and common prefixes we can further check various formats for text columns, e.g.:
- IP address - if all the prefixes up to length 4 are `number.` and all suffixes are `.number`, where number is between 0 and 255;
- SSN - if all prefixes are following the patterns: `###-` and `###-##-` and all suffixes are following the pattern `-###` (where `#` is a decimal digit);
