### ISSUE TITLE
Accounting for noise 

### ISSUE THREAD

**Issue by dandanlen** [diffix/explorer#88]
Currently we extract and then completely ignore noise values. This is fine for data visualisation purposes but for more in-depth analytics it will be important to consider noise in our calculations. 

For example, if we have a list of buckets with `count` and `count_noise` values, we might want to sum these to determine the total number of values in a given range, or in the data set. 

As a starting point, we should define how to add noisy values. For example, for the `(count_A, count_noise_A)`  + `(count_B, count_noise_B)` the result will be `(count_A + count_B, ???)`.

My initial instinct is that `???` should be the root of the sum of squares of the component noise values, ie. `sqrt(count_noise_A^2 + count_noise_B^2)`.

**Comment by sebastian** [comment]
> `sqrt(count_noise_A^2 + count_noise_B^2)`

👍  yes, this is it.

Tip: If you convert everything to variance internally, then the noise becomes a lot easier to work with! You can then convert back to standard deviation again at the end by taking the square root.

**Comment by dandanlen** [comment]
Marking this as resolved, `NoisyCount` class was added in ecfed77 , merged as part of #137.
